### PR TITLE
rebuild and add noarch: python

### PR DESCRIPTION
**Pull request by beckermr**
This PR closes #2 and #1

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/pydstool This PR is ready to merge and closes the outstanding issues on the feedstock. It is needed for the rebuild!

**Comment by beckermr** [comment]
Bump here @conda-forge/pydstool

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
This rebuild is done @conda-forge/core. Can one of you press merge?

**Comment by bgruening** [comment]
Thanks @beckermr!

**Pull request merged**
